source-list:
  # list: file:///home/lakshh/Downloads/output_h264_trim.mp4;
  # list: rtsp://root:root@192.168.6.92/cam1/h264;rtsp://admin:123456@192.168.6.91/stream0
  # list: v4l2:///dev/video0
  list: file:///home/lakshh/workspace/reid/datasets/2247f442a9784b5c959e7bead89c0313_V2/CHIRLA_dataset/videos/seq_026/cam_4.avi;file:///home/lakshh/workspace/reid/datasets/2247f442a9784b5c959e7bead89c0313_V2/CHIRLA_dataset/videos/seq_026/cam_2.avi
  # list: file:///home/lakshh/workspace/fire_smoke/research/captures/rtsp0_20260715_140145.mp4;file:///home/lakshh/workspace/fire_smoke/research/captures/cam3_20260715_140145.mp4
  # list: 
  # list: v4l2:///dev/video3
  # list: file:///home/lakshh/workspace/reid/datasets/2247f442a9784b5c959e7bead89c0313_V2/CHIRLA_dataset/videos/seq_026/cam_2.avi;
  # seq: -1
  # device: IP # USB or IP

streammux:
  batch-size: 2
  width: 1920
  height: 1080

tiler:
  width: 1920
  # width: 1792
  # width: 960
  height: 540

sink:
  qos: 0

primary-gie:  
  plugin-type: 0  
  config-file-path: /home/lakshh/workspace/reid/impl_bot/bot_sort_ds_impl/ds_include/dstest3_pgie_config.yml

secondary-gie-1:
  plugin-type: 0
  config-file-path: /home/lakshh/workspace/reid/impl_bot/bot_sort_ds_impl/ds_include/sgie_config.yml

# tracker:
#   enable: 0
#   tracker-width: 960
#   tracker-height: 544
#   gpu-id: 0
#   display-tracking-id: 0
#   ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
#   ll-config-file: /opt/nvidia/deepstream/deepstream/samples/configs/deepstream-app/config_tracker_NvDCF_max_perf.yml

osd:
  process-mode: 0
  display-text: 0
